### ISSUE TITLE
Please do disable submission of issues to this repository.

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [mauikit/index#2]
This issue is response to "http://github.com/mauikit/index/issues/1#issuecomment-661309027".

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
This should additonally occur to all of the repositories if they are duplicatory and identical to their origins.

**Comment by UriHerrera** [comment]
Please file bugs at https://invent.kde.org/groups/maui/-/issues
